name: kics-scan-to-port
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v2.1.5
        with:
          path: 'K8s/helm'
          ignore_on_exit: results
          output_path: myResults/
      - name: display kics results
        run: |
          cat myResults/results.json